/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jinger Perez Student #2013665
 */
//Importings necessary to be able to write on a txt file

import java.awt.Component;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;




public class booking extends javax.swing.JFrame {
    private Component Frame;
   
    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
        setTitle("DUB NYC Flights");//Setting title to the top of the window
        
        

  }

    //This mathod will set text fileds as empty text fields
    private void clear() {
        tfSurname.setText("");
        tfFirstname.setText("");
        tfPassp.setText("");
        tfDepart.setText("");
        tfArrive.setText("");
    }

    /*This method uses a txt file where all the input data will be placed.
     *Every text field is checked before writing on the txt file and 
     *error messages are shown on text fields
     */
    private void textFile(){
                
        
     
        /*This piece of code will check every field and will display any error*/
    
        String surname = tfSurname.getText();
        String firstname = tfFirstname.getText();
        String depart = tfDepart.getText();
        String arrv = tfArrive.getText();
        boolean flag=true;//Setting a Flag
        int pass= 0;
        
     
        
       if (surname.equals("") || surname.equals("Enter Here") 
               || surname.equals("Invalid Name")){
           flag=false;
           tfSurname.setText("Invalid  Name");
       }
       if(firstname.equals("") || firstname.equals("Enter Here") 
               || firstname.equals("Invalid Name")){
           flag=false;
           tfFirstname.setText("Invalid Name");
          
       }

        try{
            pass=Integer.parseInt(tfPassp.getText());
            
            }catch(Exception e){
                tfPassp.setText("Not an Int");
                flag=false;
            }

        if(depart.equals("")||(depart.equals("Enter Here"))
                ||(depart.equals("Invalid airport combination"))){
        tfDepart.setText("Invalid airport combination");
            flag = false;
       
        } 
        if(arrv.equals("")||(arrv.equals("Enter Here"))
                ||(arrv.equals("Invalid airport combination"))){
        tfArrive.setText("Invalid airport combination");
            flag = false;
        }
        if(depart.equals("DUB") && arrv.equals("DUB")
                ||depart.equals("NYC") && arrv.equals("NYC")){ 
            
            tfDepart.setText("Invalid airport combination");
            tfArrive.setText("Invalid airport combination");
            flag = false;   
            
        }
       
        if (((!arrv.equals("DUB")) || (!depart.equals("NYC"))) 
                && ((!depart.equals("DUB")) || (!arrv.equals("NYC")))){
            tfDepart.setText("Invalid airport combination");
            tfArrive.setText("Invalid airport combination");
            flag=false;
           
         }   
        if(flag==true){
            try{
                //Handling the txt file storing it in a String
                String archivo= ("NewBookings.txt");
                File f = new File(archivo);
                FileWriter escritor = new FileWriter(f);  
                BufferedWriter buw = new BufferedWriter(escritor);
                buw.write("Surname: " + surname + ", " + "First Name: " 
                    + firstname +  ", " + "Passport Number: " + pass 
                        + ", From: " + depart + ", " + "to: " + arrv );
                buw.close();
                JOptionPane.showMessageDialog(Frame,"Booking Completed!");
                clear();     
                    }catch(IOException e){
                        JOptionPane.showMessageDialog(Frame,"Something went wrong");
                                
                        }       
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSN = new javax.swing.JLabel();
        labelDepart = new javax.swing.JLabel();
        labelFN = new javax.swing.JLabel();
        labelPss = new javax.swing.JLabel();
        lArrive = new javax.swing.JLabel();
        enterinfo = new javax.swing.JButton();
        tfSurname = new javax.swing.JTextField();
        tfFirstname = new javax.swing.JTextField();
        tfPassp = new javax.swing.JTextField();
        tfDepart = new javax.swing.JTextField();
        tfArrive = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        itemClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelSN.setText("Surname");

        labelDepart.setText("Departing Airport Code");

        labelFN.setText("First Name");

        labelPss.setText("Passport Number");

        lArrive.setText("Arriving Airport Code");

        enterinfo.setText("Enter Information");
        enterinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterinfoActionPerformed(evt);
            }
        });

        tfSurname.setText("Enter Here");
        tfSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfSurnameFocusGained(evt);
            }
        });
        tfSurname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSurnameMouseClicked(evt);
            }
        });
        tfSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSurnameActionPerformed(evt);
            }
        });

        tfFirstname.setText("Enter Here");
        tfFirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFirstnameFocusGained(evt);
            }
        });
        tfFirstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfFirstnameMouseClicked(evt);
            }
        });
        tfFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstnameActionPerformed(evt);
            }
        });

        tfPassp.setText("Enter Here");
        tfPassp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasspFocusGained(evt);
            }
        });
        tfPassp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPasspMouseClicked(evt);
            }
        });
        tfPassp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasspActionPerformed(evt);
            }
        });

        tfDepart.setText("Enter Here");
        tfDepart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDepartFocusGained(evt);
            }
        });
        tfDepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfDepartMouseClicked(evt);
            }
        });

        tfArrive.setText("Enter Here");
        tfArrive.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfArriveFocusGained(evt);
            }
        });
        tfArrive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfArriveMouseClicked(evt);
            }
        });
        tfArrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfArriveActionPerformed(evt);
            }
        });

        menuFile.setText("File");

        itemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        itemExit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                itemExitPropertyChange(evt);
            }
        });
        menuFile.add(itemExit);

        jMenuBar1.add(menuFile);

        menuEdit.setText("Edit");

        itemClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        itemClear.setText("Clear all Fields");
        itemClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                itemClearMouseReleased(evt);
            }
        });
        itemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClearActionPerformed(evt);
            }
        });
        menuEdit.add(itemClear);

        jMenuBar1.add(menuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFN)
                                .addGap(198, 198, 198)
                                .addComponent(lArrive))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSN)
                                .addGap(210, 210, 210)
                                .addComponent(labelDepart))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(enterinfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPss)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfFirstname, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(tfPassp))))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfDepart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(tfArrive))
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSN)
                                    .addComponent(labelDepart)))
                            .addComponent(tfDepart)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfArrive)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFN)
                                    .addComponent(lArrive)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPss)
                            .addComponent(tfPassp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(enterinfo)
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterinfoActionPerformed
        textFile();

    }//GEN-LAST:event_enterinfoActionPerformed

    private void tfSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSurnameActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        // once this menu item is pressed will terminate the program
        JOptionPane.showMessageDialog(Frame,"Good Bye");
        System.exit(1);
    }//GEN-LAST:event_itemExitActionPerformed

    private void tfPasspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasspActionPerformed

    private void itemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemClearActionPerformed

    private void itemExitPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_itemExitPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_itemExitPropertyChange

    private void tfSurnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSurnameFocusGained
        tfSurname.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_tfSurnameFocusGained

    private void tfFirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFirstnameFocusGained
        tfFirstname.setText("");
    }//GEN-LAST:event_tfFirstnameFocusGained

    private void tfPasspFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasspFocusGained
        tfPassp.setText("");//Cleans the field when using tab key.
    }//GEN-LAST:event_tfPasspFocusGained

    private void tfDepartFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDepartFocusGained
        tfDepart.setText("");// Cleans the field when using tab key.

    }//GEN-LAST:event_tfDepartFocusGained

    private void tfArriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfArriveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfArriveActionPerformed

    private void tfArriveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfArriveFocusGained
        tfArrive.setText("");    // Cleans the field when using tab key.
    }//GEN-LAST:event_tfArriveFocusGained

    private void itemClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemClearMouseReleased
        JOptionPane.showMessageDialog(Frame,"Cleaning Fields");
        clear();//Will call clear method to clean up the form
        
    }//GEN-LAST:event_itemClearMouseReleased

    private void tfFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstnameActionPerformed

    private void tfSurnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSurnameMouseClicked
        tfSurname.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_tfSurnameMouseClicked

    private void tfFirstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFirstnameMouseClicked
        tfFirstname.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstnameMouseClicked

    private void tfPasspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPasspMouseClicked
        tfPassp.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_tfPasspMouseClicked

    private void tfDepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDepartMouseClicked
        tfDepart.setText("");   // TODO add your handling code here:
    }//GEN-LAST:event_tfDepartMouseClicked

    private void tfArriveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfArriveMouseClicked
        tfArrive.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_tfArriveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterinfo;
    private javax.swing.JMenuItem itemClear;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lArrive;
    private javax.swing.JLabel labelDepart;
    private javax.swing.JLabel labelFN;
    private javax.swing.JLabel labelPss;
    private javax.swing.JLabel labelSN;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JTextField tfArrive;
    private javax.swing.JTextField tfDepart;
    private javax.swing.JTextField tfFirstname;
    private javax.swing.JTextField tfPassp;
    private javax.swing.JTextField tfSurname;
    // End of variables declaration//GEN-END:variables
}
